version: '3.7'

services:
  web:
    build: ./app
    command: |
      conda run --no-capture-output -n env python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lucha
      - POSTGRES_PASSWORD=lucha
      - POSTGRES_DB=teampoolside

volumes:
  postgres_data: