version: '3.7'

services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: |
      conda run --no-capture-output -p /home/app/web/env python -m gunicorn teampoolside.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/home/app/web/static
      - media_data:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_data:/home/app/web/static
      - media_data:/home/app/web/media
    ports:
      - 6969:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
  media_data:
