version: '3.7'

services:
  web:
    image: "${WEB_IMAGE}"
    restart: unless-stopped
    command: |
      conda run --no-capture-output -p /home/app/web/env python -m gunicorn teampoolside.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/home/app/web/static
      - media_data:/home/app/web/media
    expose:
      - 8000
    env_file:
      - .env
  nginx:
    image: nginx:1.20.0-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - static_data:/home/app/web/static
      - media_data:/home/app/web/media
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


volumes:
  static_data:
  media_data:
