version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: |
      conda run --no-capture-output -p /home/app/web/env python -m gunicorn teampoolside.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/home/app/web/static
      - media_data:/home/app/web/media
    expose:
      - 8000
    env_file:
      - .env
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_data:/home/app/web/static
      - media_data:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_data:
  media_data:
